### ISSUE TITLE
Cannot read property: isAuthenticated 

### ISSUE THREAD

**Issue by mithuns** [Anupam-dagar/react-Hasura-todo#1]
Hey, I am following your tutorial published on [hackernoon](https://hackernoon.com/building-a-react-todo-app-with-hasura-graphql-engine-511b703a7ef)

I have done everything until this section **Writing queries in GraphQL**
But, I am getting this error.

```
App.js:18 Uncaught TypeError: Cannot read property 'isAuthenticated' of undefined
    at App.render (App.js:18)
    at finishClassComponent (react-dom.development.js:14105)
    at updateClassComponent (react-dom.development.js:14069)
    at beginWork (react-dom.development.js:14687)
    at performUnitOfWork (react-dom.development.js:17242)
    at workLoop (react-dom.development.js:17281)
    at HTMLUnknownElement.callCallback (react-dom.development.js:144)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:193)
    at invokeGuardedCallback (react-dom.development.js:243)
    at replayUnitOfWork (react-dom.development.js:16536)
    at renderRoot (react-dom.development.js:17374)
    at performWorkOnRoot (react-dom.development.js:18252)
    at performWork (react-dom.development.js:18159)
    at performSyncWork (react-dom.development.js:18132)
    at requestWork (react-dom.development.js:18009)
    at scheduleWork (react-dom.development.js:17802)
    at scheduleRootUpdate (react-dom.development.js:18523)
    at updateContainerAtExpirationTime (react-dom.development.js:18549)
    at updateContainer (react-dom.development.js:18580)
    at ReactRoot.push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render (react-dom.development.js:18862)
    at react-dom.development.js:19016
    at unbatchedUpdates (react-dom.development.js:18397)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:19012)
    at Object.render (react-dom.development.js:19076)
    at Module../src/index.js (index.js:7)
    at __webpack_require__ (bootstrap:782)
    at fn (bootstrap:150)
    at Object.0 (serviceWorker.js:127)
    at __webpack_require__ (bootstrap:782)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
render @ App.js:18
finishClassComponent @ react-dom.development.js:14105
updateClassComponent @ react-dom.development.js:14069
beginWork @ react-dom.development.js:14687
performUnitOfWork @ react-dom.development.js:17242
workLoop @ react-dom.development.js:17281
callCallback @ react-dom.development.js:144
invokeGuardedCallbackDev @ react-dom.development.js:193
invokeGuardedCallback @ react-dom.development.js:243
replayUnitOfWork @ react-dom.development.js:16536
renderRoot @ react-dom.development.js:17374
performWorkOnRoot @ react-dom.development.js:18252
performWork @ react-dom.development.js:18159
performSyncWork @ react-dom.development.js:18132
requestWork @ react-dom.development.js:18009
scheduleWork @ react-dom.development.js:17802
scheduleRootUpdate @ react-dom.development.js:18523
updateContainerAtExpirationTime @ react-dom.development.js:18549
updateContainer @ react-dom.development.js:18580
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:18862
(anonymous) @ react-dom.development.js:19016
unbatchedUpdates @ react-dom.development.js:18397
legacyRenderSubtreeIntoContainer @ react-dom.development.js:19012
render @ react-dom.development.js:19076
./src/index.js @ index.js:7
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ serviceWorker.js:127
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1452 The above error occurred in the <App> component:
    in App (at src/index.js:7)

```

What am I missing ?
I have the same code and everything.

**Comment by Anupam-dagar** [comment]
@mithuns Did you clone the repo or wrote the code from the image? Also do this error occur when you start the server or when you navigate to an url.
Can you provide a screenshot for the App.js?
Also can you check once if `const { isAuthenticated } = this.props.auth;` is present inside `render()` function in App.js

**Comment by Anupam-dagar** [comment]
@mithuns my bad, I just checked on it. I missed one vital information due to which the error is happening.
In index.js, add the following 2 lines
```
import { makeMainRoutes } from './routes';
const routes = makeMainRoutes();
```
and render `routes` instead of `<App />`.
Please install `history` and `react-router-dom` using
`yarn add history react-router-dom`
Make sure to import `auth0-js` in `Auth.js` and the `loading` svg in `callback.js`
Also since there is no `Home` component created yet, so you may want to comment the import and use of `Home` component in `routes.js` until it is created.
I am updating my blog with the same info.

**Comment by mithuns** [comment]
Awesome, thanks for the update. 
I will check soon, this is my first react learning app so I needed all the information.
Thanks for your efforts, I will try soon and let you know.

**Comment by Anupam-dagar** [comment]
No problem. All the best for your first react app. Let me know if you face any problem :smile:

**Comment by strongSoda** [comment]
Hey there, I am getting TypeError for **this.state.todo_text.**

<a href="https://imgur.com/KRByNCF"><img src="https://i.imgur.com/KRByNCF.png" title="source: imgur.com" /></a>

Same code. Is it the permissions for inserting in table?

**Comment by Anupam-dagar** [comment]
Hey @strongSoda, did you create a table named `todos` with the following fields in it:
```
todo_id: integer (auto increment)
todo_text: Text
todo_mark: Boolean
todo_user: Text
Chose todo_id as Primary Key.
```

**Comment by strongSoda** [comment]
Yup!

<a href="https://imgur.com/W5jLgnp"><img src="https://i.imgur.com/W5jLgnp.png" title="source: imgur.com" /></a>

**Comment by strongSoda** [comment]
Permissions for insert by user are as follows:

<a href="https://imgur.com/2RbqOBM"><img src="https://i.imgur.com/2RbqOBM.png" title="source: imgur.com" /></a>

**Comment by Anupam-dagar** [comment]
Looks like it's not the cloned code, can you show the code for the complete file as it can be a typo error too?
I just tried running locally and it's working fine.

**Comment by strongSoda** [comment]
**AddTodo.js**

<a href="https://imgur.com/obOIuAD"><img src="https://i.imgur.com/obOIuAD.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/4fyivZd"><img src="https://i.imgur.com/4fyivZd.png" title="source: imgur.com" /></a>

**QueryAddTodo.js**

<a href="https://imgur.com/2ZFdyfe"><img src="https://i.imgur.com/2ZFdyfe.png" title="source: imgur.com" /></a>

**Comment by Anupam-dagar** [comment]
@strongSoda you missed creating a constructor in your `AddTodo.js` which initialises the props and a state. You can add the following code to the top inside your component.
```
constructor(props) {
        super(props);

        this.state = {
            todo_text: "",
            todo_user: ""
        }
    }
```

For any further issues with the todo app, please create a separate issue as your issue is not relevant to the title of the issue under which this conversation is happening. Also, this generates unnecessary notifications for the original issue creator.

**Comment by strongSoda** [comment]
Whoops! Alright Corrected it. Thanks for the help.  Just one more thing. I used the default auth0 setup. So when I log in from different accounts I get the same todos. here is the code:

**logout function**
<a href="https://imgur.com/JhimOQ0"><img src="https://i.imgur.com/JhimOQ0.png" title="source: imgur.com" /></a>


**setSession**

<a href="https://imgur.com/vyNfgDh"><img src="https://i.imgur.com/vyNfgDh.png" title="source: imgur.com" /></a>

Is there any way to modify these functions to match the functionality or do i have to rewrite these?

**Comment by Anupam-dagar** [comment]
That is controlled by your Hasura console setup, you need to check for the user while fetching the todos. I guess you haven't read the blog yet, I suggest reading my blog for the app here https://hackernoon.com/building-a-react-todo-app-with-hasura-graphql-engine-511b703a7ef
It should clear many things, let me know if you still face issues after reading the blog.
